name: Build specified recipe

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v2
        with:
            python-version: '3.x'

      - name: Get pip cache dir
        id: pip-cache
        run: |
           echo "::set-output name=dir::$(pip cache dir)"

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Configure libcxx on GCC
        if: runner.os == 'Linux'
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build recipe
        run: |
          cd recipes/botan/all
          conan create --build=missing . botan/2.17.3@
